/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAaveV3IncentivesController,
  IAaveV3IncentivesControllerInterface,
} from "../../../interfaces/IAave.sol/IAaveV3IncentivesController";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "claimAllRewards",
    outputs: [
      {
        internalType: "address[]",
        name: "rewardsList",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "claimedAmounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAaveV3IncentivesController__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveV3IncentivesControllerInterface {
    return new Interface(_abi) as IAaveV3IncentivesControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAaveV3IncentivesController {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAaveV3IncentivesController;
  }
}
