/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILendingRateOracle,
  ILendingRateOracleInterface,
} from "../../../interfaces/IAave.sol/ILendingRateOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getMarketBorrowRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getMarketLiquidityRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILendingRateOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ILendingRateOracleInterface {
    return new Interface(_abi) as ILendingRateOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILendingRateOracle {
    return new Contract(address, _abi, runner) as unknown as ILendingRateOracle;
  }
}
