/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IAaveViewer {
  export type AaveAssetParamsStruct = {
    underlyingAsset: AddressLike;
    name: string;
    symbol: string;
    id: BigNumberish;
    aTokenAddress: AddressLike;
    stableDebtTokenAddress: AddressLike;
    variableDebtTokenAddress: AddressLike;
    interestRateStrategyAddress: AddressLike;
    baseLTVasCollateral: BigNumberish;
    reserveLiquidationThreshold: BigNumberish;
    reserveLiquidationBonus: BigNumberish;
    decimals: BigNumberish;
    reserveFactor: BigNumberish;
    eModeCategoryId: BigNumberish;
    usageAsCollateralEnabled: boolean;
    isActive: boolean;
    isFrozen: boolean;
    borrowingEnabled: boolean;
    stableBorrowRateEnabled: boolean;
    paused: boolean;
    variableRateSlope1: BigNumberish;
    variableRateSlope2: BigNumberish;
    stableRateSlope1: BigNumberish;
    stableRateSlope2: BigNumberish;
    baseStableBorrowRate: BigNumberish;
    baseVariableBorrowRate: BigNumberish;
    optimalUsageRatio: BigNumberish;
    debtCeiling: BigNumberish;
    debtCeilingDecimals: BigNumberish;
    borrowCap: BigNumberish;
    supplyCap: BigNumberish;
    flashLoanEnabled: boolean;
    isSiloedBorrowing: boolean;
    accruedToTreasury: BigNumberish;
    unbacked: BigNumberish;
    isolationModeTotalDebt: BigNumberish;
    eModeLtv: BigNumberish;
    eModeLiquidationThreshold: BigNumberish;
    eModeLiquidationBonus: BigNumberish;
    borrowableInIsolation: boolean;
    eModePriceSource: AddressLike;
    priceOracle: AddressLike;
    eModeLabel: string;
  };

  export type AaveAssetParamsStructOutput = [
    underlyingAsset: string,
    name: string,
    symbol: string,
    id: bigint,
    aTokenAddress: string,
    stableDebtTokenAddress: string,
    variableDebtTokenAddress: string,
    interestRateStrategyAddress: string,
    baseLTVasCollateral: bigint,
    reserveLiquidationThreshold: bigint,
    reserveLiquidationBonus: bigint,
    decimals: bigint,
    reserveFactor: bigint,
    eModeCategoryId: bigint,
    usageAsCollateralEnabled: boolean,
    isActive: boolean,
    isFrozen: boolean,
    borrowingEnabled: boolean,
    stableBorrowRateEnabled: boolean,
    paused: boolean,
    variableRateSlope1: bigint,
    variableRateSlope2: bigint,
    stableRateSlope1: bigint,
    stableRateSlope2: bigint,
    baseStableBorrowRate: bigint,
    baseVariableBorrowRate: bigint,
    optimalUsageRatio: bigint,
    debtCeiling: bigint,
    debtCeilingDecimals: bigint,
    borrowCap: bigint,
    supplyCap: bigint,
    flashLoanEnabled: boolean,
    isSiloedBorrowing: boolean,
    accruedToTreasury: bigint,
    unbacked: bigint,
    isolationModeTotalDebt: bigint,
    eModeLtv: bigint,
    eModeLiquidationThreshold: bigint,
    eModeLiquidationBonus: bigint,
    borrowableInIsolation: boolean,
    eModePriceSource: string,
    priceOracle: string,
    eModeLabel: string
  ] & {
    underlyingAsset: string;
    name: string;
    symbol: string;
    id: bigint;
    aTokenAddress: string;
    stableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    baseLTVasCollateral: bigint;
    reserveLiquidationThreshold: bigint;
    reserveLiquidationBonus: bigint;
    decimals: bigint;
    reserveFactor: bigint;
    eModeCategoryId: bigint;
    usageAsCollateralEnabled: boolean;
    isActive: boolean;
    isFrozen: boolean;
    borrowingEnabled: boolean;
    stableBorrowRateEnabled: boolean;
    paused: boolean;
    variableRateSlope1: bigint;
    variableRateSlope2: bigint;
    stableRateSlope1: bigint;
    stableRateSlope2: bigint;
    baseStableBorrowRate: bigint;
    baseVariableBorrowRate: bigint;
    optimalUsageRatio: bigint;
    debtCeiling: bigint;
    debtCeilingDecimals: bigint;
    borrowCap: bigint;
    supplyCap: bigint;
    flashLoanEnabled: boolean;
    isSiloedBorrowing: boolean;
    accruedToTreasury: bigint;
    unbacked: bigint;
    isolationModeTotalDebt: bigint;
    eModeLtv: bigint;
    eModeLiquidationThreshold: bigint;
    eModeLiquidationBonus: bigint;
    borrowableInIsolation: boolean;
    eModePriceSource: string;
    priceOracle: string;
    eModeLabel: string;
  };

  export type AavePoolParamsResponseV2Struct = {
    flashloanPremium: BigNumberish;
    assetParams: IAaveViewer.AaveAssetParamsStruct[];
  };

  export type AavePoolParamsResponseV2StructOutput = [
    flashloanPremium: bigint,
    assetParams: IAaveViewer.AaveAssetParamsStructOutput[]
  ] & {
    flashloanPremium: bigint;
    assetParams: IAaveViewer.AaveAssetParamsStructOutput[];
  };

  export type AavePoolParamsResponseV3Struct = {
    flashloanPremium: BigNumberish;
    assetParams: IAaveViewer.AaveAssetParamsStruct[];
  };

  export type AavePoolParamsResponseV3StructOutput = [
    flashloanPremium: bigint,
    assetParams: IAaveViewer.AaveAssetParamsStructOutput[]
  ] & {
    flashloanPremium: bigint;
    assetParams: IAaveViewer.AaveAssetParamsStructOutput[];
  };

  export type AavePoolStateResponseV2Struct = {
    underlyingAsset: AddressLike;
    stableDebtLastUpdateTimestamp: BigNumberish;
    liquidityIndex: BigNumberish;
    variableBorrowIndex: BigNumberish;
    liquidityRate: BigNumberish;
    variableBorrowRate: BigNumberish;
    stableBorrowRate: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    availableLiquidity: BigNumberish;
    priceInMarketReferenceCurrency: BigNumberish;
    principalStableDebt: BigNumberish;
    totalPrincipalStableDebt: BigNumberish;
    averageStableRate: BigNumberish;
    totalScaledVariableDebt: BigNumberish;
  };

  export type AavePoolStateResponseV2StructOutput = [
    underlyingAsset: string,
    stableDebtLastUpdateTimestamp: bigint,
    liquidityIndex: bigint,
    variableBorrowIndex: bigint,
    liquidityRate: bigint,
    variableBorrowRate: bigint,
    stableBorrowRate: bigint,
    lastUpdateTimestamp: bigint,
    availableLiquidity: bigint,
    priceInMarketReferenceCurrency: bigint,
    principalStableDebt: bigint,
    totalPrincipalStableDebt: bigint,
    averageStableRate: bigint,
    totalScaledVariableDebt: bigint
  ] & {
    underlyingAsset: string;
    stableDebtLastUpdateTimestamp: bigint;
    liquidityIndex: bigint;
    variableBorrowIndex: bigint;
    liquidityRate: bigint;
    variableBorrowRate: bigint;
    stableBorrowRate: bigint;
    lastUpdateTimestamp: bigint;
    availableLiquidity: bigint;
    priceInMarketReferenceCurrency: bigint;
    principalStableDebt: bigint;
    totalPrincipalStableDebt: bigint;
    averageStableRate: bigint;
    totalScaledVariableDebt: bigint;
  };

  export type AavePoolStateResponseV3Struct = {
    underlyingAsset: AddressLike;
    stableDebtLastUpdateTimestamp: BigNumberish;
    liquidityIndex: BigNumberish;
    variableBorrowIndex: BigNumberish;
    liquidityRate: BigNumberish;
    variableBorrowRate: BigNumberish;
    stableBorrowRate: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    availableLiquidity: BigNumberish;
    priceInMarketReferenceCurrency: BigNumberish;
    principalStableDebt: BigNumberish;
    totalPrincipalStableDebt: BigNumberish;
    averageStableRate: BigNumberish;
    totalScaledVariableDebt: BigNumberish;
  };

  export type AavePoolStateResponseV3StructOutput = [
    underlyingAsset: string,
    stableDebtLastUpdateTimestamp: bigint,
    liquidityIndex: bigint,
    variableBorrowIndex: bigint,
    liquidityRate: bigint,
    variableBorrowRate: bigint,
    stableBorrowRate: bigint,
    lastUpdateTimestamp: bigint,
    availableLiquidity: bigint,
    priceInMarketReferenceCurrency: bigint,
    principalStableDebt: bigint,
    totalPrincipalStableDebt: bigint,
    averageStableRate: bigint,
    totalScaledVariableDebt: bigint
  ] & {
    underlyingAsset: string;
    stableDebtLastUpdateTimestamp: bigint;
    liquidityIndex: bigint;
    variableBorrowIndex: bigint;
    liquidityRate: bigint;
    variableBorrowRate: bigint;
    stableBorrowRate: bigint;
    lastUpdateTimestamp: bigint;
    availableLiquidity: bigint;
    priceInMarketReferenceCurrency: bigint;
    principalStableDebt: bigint;
    totalPrincipalStableDebt: bigint;
    averageStableRate: bigint;
    totalScaledVariableDebt: bigint;
  };
}

export interface IAaveViewerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aavePoolParamsV2"
      | "aavePoolParamsV3"
      | "aavePoolStateV2"
      | "aavePoolStateV3"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "aavePoolParamsV2",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aavePoolParamsV3",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aavePoolStateV2",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aavePoolStateV3",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "aavePoolParamsV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aavePoolParamsV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aavePoolStateV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aavePoolStateV3",
    data: BytesLike
  ): Result;
}

export interface IAaveViewer extends BaseContract {
  connect(runner?: ContractRunner | null): IAaveViewer;
  waitForDeployment(): Promise<this>;

  interface: IAaveViewerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aavePoolParamsV2: TypedContractMethod<
    [_provider: AddressLike],
    [IAaveViewer.AavePoolParamsResponseV2StructOutput],
    "view"
  >;

  aavePoolParamsV3: TypedContractMethod<
    [_provider: AddressLike],
    [IAaveViewer.AavePoolParamsResponseV3StructOutput],
    "view"
  >;

  aavePoolStateV2: TypedContractMethod<
    [_provider: AddressLike, asset: AddressLike],
    [IAaveViewer.AavePoolStateResponseV2StructOutput],
    "view"
  >;

  aavePoolStateV3: TypedContractMethod<
    [_provider: AddressLike, asset: AddressLike],
    [IAaveViewer.AavePoolStateResponseV3StructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aavePoolParamsV2"
  ): TypedContractMethod<
    [_provider: AddressLike],
    [IAaveViewer.AavePoolParamsResponseV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "aavePoolParamsV3"
  ): TypedContractMethod<
    [_provider: AddressLike],
    [IAaveViewer.AavePoolParamsResponseV3StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "aavePoolStateV2"
  ): TypedContractMethod<
    [_provider: AddressLike, asset: AddressLike],
    [IAaveViewer.AavePoolStateResponseV2StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "aavePoolStateV3"
  ): TypedContractMethod<
    [_provider: AddressLike, asset: AddressLike],
    [IAaveViewer.AavePoolStateResponseV3StructOutput],
    "view"
  >;

  filters: {};
}
