/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAaveV3RewardsDistributorInterface extends Interface {
  getFunction(nameOrSignature: "getAllUserRewards"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllUserRewards",
    values: [AddressLike[], AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllUserRewards",
    data: BytesLike
  ): Result;
}

export interface IAaveV3RewardsDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): IAaveV3RewardsDistributor;
  waitForDeployment(): Promise<this>;

  interface: IAaveV3RewardsDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllUserRewards: TypedContractMethod<
    [assets: AddressLike[], user: AddressLike],
    [
      [string[], bigint[]] & {
        rewardsList: string[];
        unclaimedAmounts: bigint[];
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllUserRewards"
  ): TypedContractMethod<
    [assets: AddressLike[], user: AddressLike],
    [
      [string[], bigint[]] & {
        rewardsList: string[];
        unclaimedAmounts: bigint[];
      }
    ],
    "view"
  >;

  filters: {};
}
