/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAaveV3RewardsDistributor,
  IAaveV3RewardsDistributorInterface,
} from "../../../../contracts/interfaces/IAave.sol/IAaveV3RewardsDistributor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getAllUserRewards",
    outputs: [
      {
        internalType: "address[]",
        name: "rewardsList",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "unclaimedAmounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAaveV3RewardsDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveV3RewardsDistributorInterface {
    return new Interface(_abi) as IAaveV3RewardsDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAaveV3RewardsDistributor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAaveV3RewardsDistributor;
  }
}
