/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoolDataProvider,
  IPoolDataProviderInterface,
} from "../../../../contracts/interfaces/IAave.sol/IPoolDataProvider";

const _abi = [
  {
    inputs: [],
    name: "getDebtCeilingDecimals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "underlyingAsset",
        type: "address",
      },
    ],
    name: "getFlashLoanEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "flashLoanEnabled",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoolDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolDataProviderInterface {
    return new Interface(_abi) as IPoolDataProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPoolDataProvider {
    return new Contract(address, _abi, runner) as unknown as IPoolDataProvider;
  }
}
