/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CNative } from "./CNative";
export type { CToken } from "./CToken";
export type { CompoundV3Pool } from "./CompoundV3Pool";
export type { Comptroller } from "./Comptroller";
export type { ComptrollerLensInterface } from "./ComptrollerLensInterface";
export type { ComptrollerStorage } from "./ComptrollerStorage";
export type { ICompoundV2Viewer } from "./ICompoundV2Viewer";
export type { ICompoundV3Viewer } from "./ICompoundV3Viewer";
