/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAaveSol from "./IAave.sol";
export type { iAaveSol };
import type * as iBalancerSol from "./IBalancer.sol";
export type { iBalancerSol };
import type * as iCompoundSol from "./ICompound.sol";
export type { iCompoundSol };
export type { ILendingViewer } from "./ILendingViewer";
export type { ILeverager } from "./ILeverager";
export type { IWETH } from "./IWETH";
