/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICompoundV3Viewer,
  ICompoundV3ViewerInterface,
} from "../../../../contracts/interfaces/ICompound.sol/ICompoundV3Viewer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "comptroller",
        type: "address",
      },
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "compV3PoolParams",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "decimals",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "underlyingToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "underlyingDecimals",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "reserveFactorMantissa",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isListed",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "mintPaused",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "borrowPaused",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "collateralFactorMantissa",
            type: "uint256",
          },
        ],
        internalType: "struct ICompoundV3Viewer.CompV3PoolParamsResponse",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "comptroller",
        type: "address",
      },
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "compV3PoolState",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "currentNumber",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accrualNumber",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "exchangeRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "supplyRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalBorrows",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalReserves",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalCash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowCap",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isPerBlock",
            type: "bool",
          },
        ],
        internalType: "struct ICompoundV3Viewer.CompV3PoolStateResponse",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICompoundV3Viewer__factory {
  static readonly abi = _abi;
  static createInterface(): ICompoundV3ViewerInterface {
    return new Interface(_abi) as ICompoundV3ViewerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICompoundV3Viewer {
    return new Contract(address, _abi, runner) as unknown as ICompoundV3Viewer;
  }
}
