/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ReentrancyLock,
  ReentrancyLockInterface,
} from "../../libraries/ReentrancyLock";

const _abi = [
  {
    inputs: [],
    name: "ReentrancyLock",
    type: "error",
  },
] as const;

export class ReentrancyLock__factory {
  static readonly abi = _abi;
  static createInterface(): ReentrancyLockInterface {
    return new Interface(_abi) as ReentrancyLockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyLock {
    return new Contract(address, _abi, runner) as unknown as ReentrancyLock;
  }
}
